### ISSUE TITLE
Downloads files without extension and name

### ISSUE THREAD

**Issue by viktor02** [janw/podcast-archiver#19]
Example of the downloaded file: nOKu57Ci1T0r

Win7, python 3.8.1

**Comment by janw** [comment]
Thanks for you reporting this. Can you provide a feed url to which this applies?

**Comment by androbwebb** [comment]
I have this problem too: http://feeds.feedburner.com/TheRoundTableOfGentlemen

**Comment by androbwebb** [comment]
It happens when the url in the feed redirects to a cdn/s3 looking url. I.e. `http://feedproxy.google.com/~r/TheRoundTableOfGentlemen/~5/p0KVJFuiqx8/357803189-roundtableofgentlemen-episode-347-hollywood-bear-lebrities.mp3` redirects to `https://cf-media.sndcdn.com/6EZDqGg12Pvl?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vNkVaRHFHZzEyUHZsIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNTg5ODUxMTkyfX19XX0_&Signature=NijZg2Qc0K9H~HH4tLw0EL4YvvdfLcAmE3NXN2XRz9iHxkz~cRob-3mN6OyvNdTplm356setw65bKxY4UQo9YLqBpWJ-XEVpIcd~aRj6Jt1tK7j3VH7pbolAgudoHc27CH6M4FmBysPYoy6~1upZ7UK8XEH1DCSnn~rCKbuvi-CZj0EI2Wlc3AtDFfz-BbkSONWHi78K2DnHO5brN2m0Ftd4PfOKe5NyoEVLjngpHqpVUK7XeLNet6kj8QU14fmcNF4pytSpFKpDsYTaFAhIMvY8tLvIYDcpy0iM0RoZx64avEqySC~qWHJTFCOFKs3iRr3P5ygnBMKEpVPtaR96tg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ`

**Comment by androbwebb** [comment]
Quickfix is to comment out this line: https://github.com/janw/podcast-archiver/blob/master/podcast_archiver.py#L343

**Comment by janw** [comment]
@androbwebb Thanks for this, I'll look into it shortly!

**Comment by janw** [comment]
@androbwebb Would you mind testing the `add-robust-filename-resolving` branch and see if that fixes the issue for you?

**Comment by androbwebb** [comment]
@janw Just tested - worked perfectly!

**Comment by janw** [comment]
Thanks @androbwebb!
